name: Build OpenWrt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Platform (e.g., x86_64, ramips/mt7621)'
        required: true
        default: 'armvirt_64'
      subtarget:
        description: 'Subtarget (if applicable)'
        required: false
      profile:
        description: 'Device Profile (e.g., generic, redmi_ax6s)'
        required: false
        default: 'generic'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget \
        python3-distutils python3-setuptools rsync subversion swig time \
        xsltproc zlib1g-dev

    - name: Clone OpenWrt source
      run: |
        git clone https://github.com/openwrt/openwrt.git openwrt
        cd openwrt
        git pull
        git checkout master  # 或者指定版本号

    - name: Update feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply custom configuration
      run: |
        cd openwrt
        # 复制用户自定义的配置文件
        cp ../.config .

    - name: Customize firmware
      run: |
        cd openwrt
        # 执行第一个自定义脚本
        ../diy-part1.sh
        # 执行第二个自定义脚本（已整合原diy-part3.sh的功能）
        ../diy-part2.sh

    - name: Build OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) download || make -j1 download V=s
        make -j$(nproc) || make -j1 V=s

    - name: Compress firmware
      run: |
        cd openwrt/bin/targets
        tar -czvf openwrt-firmware.tar.gz *
        mv openwrt-firmware.tar.gz ../../../

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt-Firmware
        path: openwrt/bin/targets/**/*.bin

    - name: Send email with firmware
      uses: dawidd6/action-send-mail@v3
      continue-on-error: true  # 邮件发送失败不影响整个工作流
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: OpenWrt固件编译完成
        body: |
          您好，OpenWrt固件已编译完成。
          编译时间: ${{ github.run_id }}
          提交哈希: ${{ github.sha }}
          
          可以从以下链接下载固件:
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts
          
          如果附件下载失败，请使用上面的链接下载。
        to: null_mail@foxmail.com
        from: GitHub Actions
        secure: true
        files: openwrt-firmware.tar.gz
